server:
  port: 8090

mybatis:
  #对应实体类包名
  type-aliases-package: com.nyaxs.nyastore.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  #config-location: classpath:mybatis/mybatis-config.xml

spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/nya_store?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/nya_store?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
